#!/bin/bash

echo "🚀 MealLens Monorepo Deployment Guide"
echo "====================================="
echo ""

echo "📋 Your repository structure:"
echo "MealLens-Beta/"
echo "├── frontend/          (Vercel deployment)"
echo "├── backend/           (Render deployment)"
echo "└── render.yaml        (Render configuration)"
echo ""

echo "🔧 Backend Deployment (Render):"
echo "1. Go to: https://dashboard.render.com"
echo "2. Click 'New +' → 'Web Service'"
echo "3. Connect your GitHub repo"
echo "4. Configure:"
echo "   - Root Directory: (leave empty)"
echo "   - Build Command: cd backend && pip install -r requirements.txt"
echo "   - Start Command: cd backend && gunicorn wsgi:app"
echo "   - Health Check: /health"
echo ""

echo "🎨 Frontend Deployment (Vercel):"
echo "1. Go to: https://vercel.com/dashboard"
echo "2. Click 'New Project'"
echo "3. Import your GitHub repo"
echo "4. Configure:"
echo "   - Root Directory: frontend"
echo "   - Build Command: npm run build"
echo "   - Output Directory: dist"
echo ""

echo "🔗 Environment Variables:"
echo ""
echo "Backend (Render):"
echo "- SUPABASE_URL"
echo "- SUPABASE_ANON_KEY"
echo "- SUPABASE_SERVICE_ROLE_KEY"
echo "- PAYSTACK_SECRET_KEY"
echo "- PAYSTACK_PUBLIC_KEY"
echo "- JWT_SECRET"
echo "- DATABASE_URL"
echo "- CORS_ORIGINS"
echo ""
echo "Frontend (Vercel):"
echo "- VITE_API_URL=https://your-backend-app.onrender.com"
echo "- VITE_SUPABASE_URL"
echo "- VITE_SUPABASE_ANON_KEY"
echo "- VITE_PAYSTACK_PUBLIC_KEY"
echo ""

echo "✅ Both services will auto-deploy on every Git push!"
echo "🎯 Your URLs will be:"
echo "- Frontend: https://your-app-name.vercel.app"
echo "- Backend: https://your-backend-app.onrender.com"